name: Pypi Analysis on BigQuery

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      name: Update status
      run: echo "Deployed"
    environment:
      name: Production